name: "tgallant.github.io"
description: "functional programming and web dev"
url: "https://tgallant.github.io"
paginate: 10
exclude: ['Gemfile', 'Gemfile.lock', 'bower.json']
assets:
  compress:
    js: uglifier
    css: sass

markdown: rdiscount
permalink: none 
highlighter: rouge